### ISSUE TITLE
HTML in export

### ISSUE THREAD

**Issue by Remo** [Remo/concrete5-attribute-forms#5]
When I use a `select` attribute I get some HTML code in the output. br's could be replaced by \n and trimmed so that we don't have them at the end. Anything else we have to take care of? 

![image](https://cloud.githubusercontent.com/assets/129864/12511225/e8a7c650-c10f-11e5-9780-fada4cf7b12f.png)

**Comment by HamedDarragi** [comment]
Okay and what about textarea?
It's full of HTML code

**Comment by Remo** [comment]
I guess we can't easily convert HTML to ExcelML with the library we are using?
If that's the case we should probably convert line breaks and remove all other HTML tags.

**Comment by HamedDarragi** [comment]
That's a good idea,
Okay i agree.

**Comment by Remo** [comment]
look at that, maybe we could even output HTML code!
https://github.com/PHPOffice/PHPExcel/issues/794#issuecomment-173214435

**Comment by HamedDarragi** [comment]
Good, will give it a try
